version: '3.8'

services:
  # Service Backend
  back:
    build: ./back
    container_name: projet-back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=nest_user
      - DB_PASSWORD=nest_password
      - DB_NAME=audiophile_db
    depends_on:
      - db
    restart: unless-stopped

  # Service Frontend
  front:
    build: ./front
    container_name: projet-front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - back
    environment:
      - VITE_API_URL=http://localhost:3000

  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: projet-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nest_user
      - POSTGRES_PASSWORD=nest_password
      - POSTGRES_DB=audiophile_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Adminer pour la gestion de la base de données
  adminer:
    image: adminer
    container_name: projet-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: